services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
     - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    ports:
     - "5433:5432"
volumes:
  pgdata: