version: '3.8'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: statistic
    ports:
      - "5433:5432"
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
    external: true
